<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>MidnightToggle</AssemblyName>
    <RootNamespace>MidnightToggle</RootNamespace>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>

  <Import Project="$(CSII_TOOLPATH)\Mod.props" />

  <ItemGroup>
    <Reference Include="Game">
      <HintPath>$(ManagedPath)\Game.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Colossal.Core">
      <HintPath>$(ManagedPath)\Colossal.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Colossal.Logging">
      <HintPath>$(ManagedPath)\Colossal.Logging.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Colossal.UI.Binding">
      <HintPath>$(ManagedPath)\Colossal.UI.Binding.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.Entities">
      <HintPath>$(ManagedPath)\Unity.Entities.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Unity.Collections">
        <HintPath>$(ManagedPath)\Unity.Collections.dll</HintPath>
        <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Import Project="$(CSII_TOOLPATH)\Mod.targets" />

</Project>